project:
  type: website
  output-dir: docs

website:
  title: "MATH 244: Paid vs. Unpaid Labor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datacleaning.qmd  
        text: "Data & Cleaning"
      - href: methodology.qmd  
        text: "Methodology"
      - href: resultsdiscussion.qmd  
        text: "Results & Discussion"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



